# -*- coding: utf-8 -*-
"""Outlier Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_bVFaxLqcCpOixa7v0XMaHXNDE6StnP9
"""

from google.colab import files
import os

# Create the expected directory structure
os.makedirs('raw_data', exist_ok=True)
os.makedirs('outputs', exist_ok=True)

print("Please upload your simulated CSV files (transactions.csv, daily_sessions.csv, scratch_cards.csv):")
uploaded = files.upload()

# Move them into raw_data if they were uploaded directly
for filename in uploaded.keys():
    if filename.endswith('.csv'):
        os.rename(filename, f'raw_data/{filename}')
print("✅ Project files staged in raw_data/")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# ── BRANDED VISUAL ARCHITECTURE ──
MYNTRA_PALETTE = {
    'primary': '#1A0A2A',    # Deep Purple
    'accent': '#E71C5A',     # Vibrant Pink
    'dark_gray': '#2D2D2D',  # Dark Slate Gray
    'light_bg': '#F9F9FB'    # Clean Light Gray
}

sns.set_theme(style="whitegrid")
plt.rcParams.update({
    'font.size': 10,
    'axes.labelsize': 12,
    'axes.titlesize': 13,
    'axes.facecolor': MYNTRA_PALETTE['light_bg'],
    'grid.color': '#E2E2E6'
})

print("📊 Loading simulation tables for 3-plot diagnostic matrix...")

# Load the raw data streams from your workspace pipeline
df_sess = pd.read_csv('raw_data/daily_sessions.csv')
df_sc = pd.read_csv('raw_data/scratch_cards.csv')
df_txn = pd.read_csv('raw_data/transactions.csv')

# --- SETUP 1x3 HORIZONTAL DISPLAY MATRIX ---
fig, axes = plt.subplots(1, 3, figsize=(20, 6))

def render_analyst_boxplot(series, ax, title, ylabel, unit=""):
    """
    Renders a premium, branded boxplot enriched with foundational data metadata:
    Sample Size, Mean, Median, and Outlier Percentage based on standard IQR fences.
    """
    clean_series = series.dropna()

    # Calculate fundamental descriptive statistics
    n_size = len(clean_series)
    median_val = clean_series.median()
    mean_val = clean_series.mean()

    # Calculate IQR Fences
    q1, q3 = clean_series.quantile(0.25), clean_series.quantile(0.75)
    iqr = q3 - q1
    upper_fence = q3 + 1.5 * iqr
    lower_fence = q1 - 1.5 * iqr

    # Quantify precise outlier density
    outliers = clean_series[(clean_series < lower_fence) | (clean_series > upper_fence)]
    outlier_pct = (len(outliers) / n_size) * 100 if n_size > 0 else 0.0

    # Render Plot with Myntra colorways
    sns.boxplot(
        y=clean_series,
        ax=ax,
        color=MYNTRA_PALETTE['accent'],
        width=0.35,
        flierprops={'marker': 'o', 'markerfacecolor': MYNTRA_PALETTE['primary'], 'markeredgecolor': 'none', 'markersize': 4},
        medianprops={'color': MYNTRA_PALETTE['primary'], 'linewidth': 2},
        showmeans=True,
        meanprops={'marker':'D', 'markerfacecolor': 'white', 'markeredgecolor': MYNTRA_PALETTE['primary'], 'markersize': 5}
    )

    # Plot standard statistical upper reference fence
    ax.axhline(upper_fence, color=MYNTRA_PALETTE['dark_gray'], linestyle='--', alpha=0.8, linewidth=1.2,
               label=f'Upper Fence ({upper_fence:.1f}{unit})')

    # Inject metadata block directly onto the plot canvas
    metadata_text = (
        f"Sample Size (N): {n_size:,}\n"
        f"Mean: {mean_val:.2f}{unit}\n"
        f"Median: {median_val:.2f}{unit}\n"
        f"Outlier Rate: {outlier_pct:.2f}%"
    )

    ax.text(
        0.95, 0.95, metadata_text,
        transform=ax.transAxes,
        verticalalignment='top',
        horizontalalignment='right',
        bbox=dict(boxstyle='round,pad=0.4', facecolor='white', edgecolor='#D0D0D5', alpha=0.9),
        fontfamily='monospace',
        fontsize=9,
        color=MYNTRA_PALETTE['primary']
    )

    # Structural cleanups
    ax.set_title(title, fontweight='bold', color=MYNTRA_PALETTE['primary'], pad=12)
    ax.set_ylabel(ylabel, color=MYNTRA_PALETTE['dark_gray'])
    ax.set_ylim(bottom=0) # Hard clamp at zero to eliminate illogical negative space extensions
    ax.legend(loc='lower right', frameon=True, facecolor='white')

# ── 1. PLATFORM ENGAGEMENT SESSION DURATION ──
render_analyst_boxplot(
    series=df_sess['session_dur_min'],
    ax=axes[0],
    title='1. Platform Engagement: Daily Session Durations',
    ylabel='Duration (Minutes)',
    unit=' min'
)

# ── 2. INCENTIVE STREAM SCRATCH CARD REWARDS ──
render_analyst_boxplot(
    series=df_sc['card_amount_rs'],
    ax=axes[1],
    title='2. Incentive Stream: Scratch Card Values',
    ylabel='Card Reward Amount (Rs.)',
    unit=' Rs'
)

# ── 3. BASKET ECONOMICS ORDER VALUE ──
render_analyst_boxplot(
    series=df_txn['order_value_rs'],
    ax=axes[2],
    title='3. Basket Economics: Order Value Distribution',
    ylabel='Order Value (Rs.)',
    unit=' Rs'
)

plt.tight_layout()
os.makedirs('outputs', exist_ok=True)
plt.savefig('outputs/operational_outlier_matrix.png', dpi=300, facecolor='white')
plt.show()

print("✅ Streamlined operational plots generated successfully.")

# --- PRINT REFINED BUSINESS ANALYSIS ---
print("\n" + "="*80)
print("💼 MYNTRA INCENTIVE BLEED PROJECT — METRIC ECOSYSTEM DIAGNOSTIC")
print("="*80)

print("\n📊 VISUAL CONTEXTUAL ANALYSIS:")
print("-" * 50)

print("📌 1. PLATFORM ENGAGEMENT (Daily Session Durations)")
print("   • Observation: Pronounced right-tail skew with extended upper-bound outliers.")
print("   • Domain Truth: Long browsing sessions naturally occur during festive campaigns ")
print("     and high-involvement shopping.")
print("   • Pipeline Action: RETAINED. These represent legitimate, high-intent customer engagement.")

print("\n📌 2. INCENTIVE STREAM (Distributed Scratch Card Values)")
print("   • Observation: Distinct high-value anomalous points isolated above the standard IQR.")
print("   • Domain Truth: Higher-value scratch cards are intentionally rare promotional incentives ")
print("     rather than anomalies.")
print("   • Pipeline Action: RETAINED. Removing them would severely distort the true incentive distribution.")

print("\n📌 3. BASKET ECONOMICS (Order Value Distribution)")
print("   • Observation: Clear, visible luxury-tail spending points extending past the upper limit.")
print("   • Domain Truth: These represent premium shoppers, multiple-item carts, and festival purchases.")
print("   • Pipeline Action: RETAINED. This is highly profitable Normal Behavior, not an operational bug.")

print("\n" + "="*80)
print("✅ DIAGNOSTIC SUMMARY COMPLETE")
print("="*80)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# ── BRANDED VISUAL ARCHITECTURE ──
MYNTRA_PALETTE = {
    'primary': '#1A0A2A',    # Deep Purple
    'accent': '#E71C5A',     # Vibrant Pink
    'dark_gray': '#2D2D2D',  # Dark Slate Gray
    'light_bg': '#F9F9FB'    # Clean Light Gray
}

sns.set_theme(style="whitegrid")
plt.rcParams.update({
    'font.size': 10,
    'axes.labelsize': 12,
    'axes.titlesize': 13,
    'axes.facecolor': MYNTRA_PALETTE['light_bg'],
    'grid.color': '#E2E2E6'
})

print("📊 Loading customer master table for demographic baseline rendering...")

# Load the customer master stream from your workspace pipeline
df_cust = pd.read_csv('raw_data/customers.csv')

# --- SETUP 1x2 HORIZONTAL DISPLAY MATRIX ---
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

def render_demographic_boxplot(series, ax, title, ylabel, unit=""):
    """
    Renders a premium, branded boxplot for bounded demographic attributes,
    displaying Sample Size, Mean, Median, and Outlier Rates to establish statistical baselines.
    """
    clean_series = series.dropna()

    # Calculate fundamental descriptive statistics
    n_size = len(clean_series)
    median_val = clean_series.median()
    mean_val = clean_series.mean()

    # Calculate IQR Fences
    q1, q3 = clean_series.quantile(0.25), clean_series.quantile(0.75)
    iqr = q3 - q1
    upper_fence = q3 + 1.5 * iqr
    lower_fence = q1 - 1.5 * iqr

    # Quantify precise outlier density
    outliers = clean_series[(clean_series < lower_fence) | (clean_series > upper_fence)]
    outlier_pct = (len(outliers) / n_size) * 100 if n_size > 0 else 0.0

    # Render Plot with Myntra colorways
    sns.boxplot(
        y=clean_series,
        ax=ax,
        color=MYNTRA_PALETTE['accent'],
        width=0.35,
        flierprops={'marker': 'o', 'markerfacecolor': MYNTRA_PALETTE['primary'], 'markeredgecolor': 'none', 'markersize': 4},
        medianprops={'color': MYNTRA_PALETTE['primary'], 'linewidth': 2},
        showmeans=True,
        meanprops={'marker':'D', 'markerfacecolor': 'white', 'markeredgecolor': MYNTRA_PALETTE['primary'], 'markersize': 5}
    )

    # Plot upper and lower statistical reference fences
    ax.axhline(upper_fence, color=MYNTRA_PALETTE['dark_gray'], linestyle='--', alpha=0.5, linewidth=1.2,
               label=f'Upper Fence ({upper_fence:.1f}{unit})')
    ax.axhline(lower_fence, color=MYNTRA_PALETTE['dark_gray'], linestyle='--', alpha=0.5, linewidth=1.2,
               label=f'Lower Fence ({lower_fence:.1f}{unit})')

    # Inject metadata block directly onto the plot canvas
    metadata_text = (
        f"Sample Size (N): {n_size:,}\n"
        f"Mean: {mean_val:.2f}{unit}\n"
        f"Median: {median_val:.2f}{unit}\n"
        f"Outlier Rate: {outlier_pct:.2f}%"
    )

    ax.text(
        0.95, 0.95, metadata_text,
        transform=ax.transAxes,
        verticalalignment='top',
        horizontalalignment='right',
        bbox=dict(boxstyle='round,pad=0.4', facecolor='white', edgecolor='#D0D0D5', alpha=0.9),
        fontfamily='monospace',
        fontsize=9,
        color=MYNTRA_PALETTE['primary']
    )

    # Structural cleanups
    ax.set_title(title, fontweight='bold', color=MYNTRA_PALETTE['primary'], pad=12)
    ax.set_ylabel(ylabel, color=MYNTRA_PALETTE['dark_gray'])
    ax.set_ylim(bottom=0)  # Demographic variables cannot realistically go below zero
    ax.legend(loc='lower right', frameon=True, facecolor='white')

# ── 1. CUSTOMER AGE DISTRIBUTION ──
render_demographic_boxplot(
    series=df_cust['age'],
    ax=axes[0],
    title='1. Demographics: Customer Age Distribution',
    ylabel='Age (Years)',
    unit=' yrs'
)

# ── 2. SIGNUP TENURE DISTRIBUTION ──
render_demographic_boxplot(
    series=df_cust['signup_tenure_weeks'],
    ax=axes[1],
    title='2. Platform Profile: Signup Tenure',
    ylabel='Tenure (Weeks)',
    unit=' wks'
)

plt.tight_layout()
os.makedirs('outputs', exist_ok=True)
plt.savefig('outputs/demographic_profile_matrix.png', dpi=300, facecolor='white')
plt.show()

print("✅ Demographic profile baselines generated. Notice the absence of extreme tails here!")