# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MKkLYgswY1Ja3bR60UJPJvBt3OfJ_awn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import wilcoxon

# 1. Load Data
df = pd.read_excel("price_parity_raw.xlsx")

# 2. Basic Inspection
print("--- INITIAL SCHEMA ---")
print(df.head())
print(df.columns)
print(df.isnull().sum())
print(df[['myntra_method', 'comp_method','floor_used']].head())

# 3. Data Cleaning
df = df.dropna(subset=["price_delta", "competitor_price", "price_delta_pct"])
df = df.drop(columns=["comp_method", "myntra_method", "competitor_img_url"])

print("\n--- CLEANED SCHEMA ---")
print(df[["price_delta", "competitor_price", "price_delta_pct"]].isnull().sum())
print(df.columns)
print(df["price_delta_pct"].describe())

# 4. Feature Engineering
df['delta_pct'] = ((df['myntra_price'] - df['competitor_price']) / df['competitor_price'] * 100).round(2)
print("\n--- CALCULATED DELTA PERCENTAGES ---")
print(df['delta_pct'].head(20))

# 5. Outlier Detection (IQR)
q3 = df['delta_pct'].quantile(0.75)
q1 = df['delta_pct'].quantile(0.25)
iqr = q3 - q1
upperbound = q3 + 1.5 * iqr
lowerbound = q1 - 1.5 * iqr

print(f"\nIQR Upperbound: {upperbound}")
print(f"IQR Lowerbound: {lowerbound}")

# 6. Data Quality Labeling
df["data_quality"] = "valid"
df.loc[df["delta_pct"].abs() > 21.32625, "data_quality"] = "review"
df.loc[df["delta_pct"].abs() > 100, "data_quality"] = "scraping_error"

valid = df[df['data_quality'] == 'valid'].copy()
valid_review = df[df["data_quality"] != "scraping_error"]

print("\n--- QUALITY DISTRIBUTION ---")
print(df['data_quality'].value_counts())

# 7. Statistical Testing (Wilcoxon)
valid_median = valid["delta_pct"].median()
valid_stat, valid_p = wilcoxon(valid["delta_pct"])

vr_median = valid_review["delta_pct"].median()
vr_stat, vr_p = wilcoxon(valid_review["delta_pct"])

# 8. Aggregations
platform_parity = valid.groupby('competitor_platform')['delta_pct'].median().sort_values()
category_parity = valid.groupby(['category', 'competitor_platform'])['delta_pct'].median().unstack()

# ==============================================================================
# SAVE ASSETS TO FILE SYSTEM (EXECUTES HEADLESSLY IN SCRIPT)
# ==============================================================================

# 1. Save Boxplot: Percentage Delta
plt.figure(figsize=(10, 4))
sns.boxplot(x="price_delta_pct", data=df, color='skyblue')
plt.title("Boxplot of Price Delta Percentage (Myntra vs Competitors)")
plt.xlabel("Percentage Difference (%)")
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.savefig("price_delta_pct_boxplot.png", bbox_inches='tight', dpi=300)
plt.close()

# 2. Save Boxplot: Absolute Delta
plt.figure(figsize=(10, 4))
sns.boxplot(x="price_delta", data=df, color='salmon')
plt.title("Boxplot of Absolute Price Delta (INR)")
plt.xlabel("Price Difference (₹)")
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.savefig("price_delta_boxplot.png", bbox_inches='tight', dpi=300)
plt.close()

# 3. Save Heatmap: Category vs Platform Matrix
plt.figure(figsize=(12, 8))
sns.heatmap(category_parity, annot=True, cmap='RdYlGn_r', center=0, fmt=".1f")
plt.title("Price Parity Heatmap: Myntra vs Competitors by Category")
plt.savefig("category_parity_heatmap.png", bbox_inches='tight', dpi=300)
plt.close()

# 4. Save Structured Data Tables
platform_parity.to_csv("platform_parity_summary.csv", header=["median_delta_pct"])
category_parity.to_excel("category_vs_platform_parity_matrix.xlsx")

# 5. Save Summary Statistical Text Report
with open("price_parity_statistical_report.md", "w", encoding="utf-8") as f:
    f.write("# Project Siphon: Price Parity Statistical Report\n\n")

    f.write("## 1. Valid Samples Analysis (Excluding Outliers)\n")
    f.write(f"- **Sample Size**: {len(valid)}\n")
    f.write(f"- **Median Delta %**: {round(valid_median, 2)}%\n")
    f.write(f"- **Wilcoxon Statistic**: {valid_stat}\n")
    f.write(f"- **p-value**: {round(valid_p, 4)}\n\n")
    if valid_p > 0.05:
        f.write("> **Conclusion**: Fail to reject H0 → No significant price inflation / broad parity holds.\n\n")
    else:
        f.write("> **Conclusion**: Reject H0 → Significant pricing difference detected.\n\n")

    f.write("## 2. Valid + Review Samples Analysis\n")
    f.write(f"- **Sample Size**: {len(valid_review)}\n")
    f.write(f"- **Median Delta %**: {round(vr_median, 2)}%\n")
    f.write(f"- **Wilcoxon Statistic**: {vr_stat}\n")
    f.write(f"- **p-value**: {round(vr_p, 4)}\n\n")
    if vr_p > 0.05:
        f.write("> **Conclusion**: Fail to reject H0 → No significant inflation even including large deltas.\n\n")
    else:
        f.write("> **Conclusion**: Reject H0 → Significant pricing difference appears when review-tier included.\n\n")

    f.write("## 3. Platform Parity Rankings (Median Delta %)\n")
    f.write("```text\n")
    f.write(platform_parity.to_string())
    f.write("\n```\n\n")

    f.write("## 4. Category vs Platform Matrix (Median Delta %)\n")
    f.write("```text\n")
    f.write(category_parity.to_string())
    f.write("\n```\n")

print("\n[SUCCESS] Pipeline executed completely. Visualizations, spreadsheet tables, and statistical reports have been written to disk.")